apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qyz7y5a4n-dotnet-basic
  janus-idp.io/tekton: qyz7y5a4n-dotnet-basic
  backstage.io/kubernetes-id: qyz7y5a4n-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qyz7y5a4n-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
